const $ = (selector) => document.querySelector(selector);
const toast = $('.toast');
const api = async (url, options = {}) => { const headers = { 'Content-Type': 'application/json', ...(options.headers || {}) }; const token = localStorage.getItem('careersync-session'); if (token) headers.Authorization = `Bearer ${token}`; if (url.startsWith('/api/auth/login/')) { try { const payload = JSON.parse(options.body || '{}'); const selectedRole = $('#login-form [name="role"]')?.value; if (selectedRole) { payload.role = selectedRole; options = { ...options, body: JSON.stringify(payload) }; } } catch {} } const response = await fetch(url, { ...options, headers }); const data = await response.json(); if (!response.ok) throw new Error(data.error); return data; };
function message(text) { toast.textContent = text; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 3000); }
function escape(text) { return String(text).replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[c])); }
function employeeJobs(jobs) { const categories = [...new Set(jobs.map((job) => job.category || 'Other'))]; return `<p class="eyebrow">PERSONALIZED FOR YOU</p><div class="hello"><div><h1>Your best<br />next move <span>✦</span></h1><p>${jobs.length} live opportunities ranked by fit.</p></div><div class="portrait">AT</div></div><section class="career-score"><div><p>CAREER READINESS</p><strong>86<span>/100</span></strong><small>Skills profile is up to date</small></div><div class="ring"><b>86</b></div></section><div class="section-title"><h2>Best matches</h2><select class="category-filter" id="employee-category-filter"><option value="all">All categories</option>${categories.map((category) => `<option value="${escape(category)}">${escape(category)}</option>`).join('')}</select></div><div id="job-results">${jobs.map((job) => `<article class="job-card" data-category="${escape(job.category || 'Other')}"><div class="company-logo lime">N</div><div class="job-content"><span class="match">${job.score}% MATCH</span><h3>${escape(job.title)}</h3><p>Northstar Labs · ${escape(job.location)}</p><div class="tags"><span>${escape(job.category || 'Other')}</span><span>${escape(job.employmentType || 'Permanent')}</span><span>${escape(job.paymentFrequency || 'Monthly')} · ${escape(job.salary)}</span></div><details><summary>View job details and match reasons</summary><p>${escape(job.description || '')}</p><p>Hours: ${escape(job.workHoursPerDay || 8)} per day · Off-days: ${escape(job.offDays || 'To be discussed')} · Payment: ${escape(job.paymentMethod || 'To be discussed')}</p><ul>${job.factors.map((f) => `<li>${escape(f)}</li>`).join('')}</ul></details></div><button class="apply ${job.applied ? 'done' : ''}" data-job="${job.id}" ${job.applied ? 'disabled' : ''}>${job.applied ? 'Applied' : 'Apply'}</button></article>`).join('')}</div>`; }
async function renderEmployee(page = 'jobs') { const el = $('#employee-content'); el.innerHTML = '<p class="loading">Loading your opportunities…</p>'; try { if (page === 'applications') { const { applications } = await api('/api/my-applications'); el.innerHTML = `<p class="eyebrow">APPLICATIONS</p><h1>Your progress</h1>${applications.length ? applications.map((a) => `<article class="job-card"><div class="company-logo lime">N</div><div class="job-content"><h3>${escape(a.job.title)}</h3><p>Northstar Labs · submitted ${new Date(a.submittedAt).toLocaleDateString()}</p></div><span class="status ${a.status}">${a.status}</span>${a.cancellable ? `<button class="cancel-application" data-cancel="${a.id}">Cancel</button>` : ''}</article>`).join('') : '<div class="empty"><h3>No applications yet</h3><p>Return to Matches to apply for a role.</p></div>'}`; } else { const { jobs } = await api('/api/jobs'); el.innerHTML = employeeJobs(jobs); } } catch (error) { el.innerHTML = `<p class="error">${escape(error.message)}</p>`; } }
function candidateRow(candidate) { return `<div class="candidate"><div class="candidate-avatar purple">AT</div><div class="candidate-info"><h3>${escape(candidate.candidate.name)}</h3><p>${escape(candidate.candidate.title)} · ${escape(candidate.job.title)}</p><div class="skills">${candidate.candidate.skills.map((s) => `<span>${escape(s)}</span>`).join('')}</div></div><div class="score"><strong>${candidate.score}%</strong><small>match</small></div><select class="review" data-application="${candidate.id}"><option value="submitted" ${candidate.status === 'submitted' ? 'selected' : ''}>Submitted</option><option value="reviewing" ${candidate.status === 'reviewing' ? 'selected' : ''}>Reviewing</option><option value="shortlisted" ${candidate.status === 'shortlisted' ? 'selected' : ''}>Shortlist</option><option value="interviewing" ${candidate.status === 'interviewing' ? 'selected' : ''}>Interview</option><option value="rejected" ${candidate.status === 'rejected' ? 'selected' : ''}>Reject</option></select><button class="schedule" data-schedule="${candidate.id}" data-candidate="${escape(candidate.candidate.name)}">Schedule</button></div>`; }
async function renderEmployer() { const el = $('#employer-content'); el.innerHTML = '<p class="loading">Loading dashboard…</p>'; try { const data = await api('/api/employer/dashboard'); const { metrics, company, candidates } = data; el.innerHTML = `<header class="dash-header"><div><p class="eyebrow">OVERVIEW</p><h1>Hiring, made clearer.</h1></div><div class="header-actions"><button class="primary" id="post-job">+ Post a job</button></div></header><section class="metrics"><article><p>Active openings</p><strong>${metrics.activeJobs}</strong><span class="positive">Live on CareerSync</span></article><article><p>Applicants</p><strong>${metrics.applicants}</strong><span class="positive">Across your roles</span></article><article><p>Avg. time to shortlist</p><strong>${metrics.responseDays} <small>days</small></strong><span class="positive">Benchmark target: 3 days</span></article><article><p>Company trust score</p><strong>${company.trustScore} <small>/ 5</small></strong><span class="trust">● Verified</span></article></section><section class="dashboard-grid"><div class="panel candidates"><div class="panel-head"><div><h2>Candidate pipeline</h2><p>AI rank is a suggestion for human review.</p></div></div>${candidates.length ? candidates.map(candidateRow).join('') : '<div class="empty"><h3>No applications yet</h3><p>Publish a role and candidates will appear here.</p></div>'}</div><div class="right-stack"><section class="panel insight"><div class="sparkle">✦</div><p class="eyebrow">AI SAFETY</p><h3>Explain before you decide</h3><p>Matches only use job-relevant skills, work preferences and location. Recruiters make every hiring decision.</p></section><section class="panel trust-panel"><div class="panel-head"><h2>Trust profile</h2><span class="verified">● Verified</span></div><div class="trust-score"><strong>${company.trustScore}</strong><div><div class="stars">★★★★★</div><p>Based on verified feedback</p></div></div><div class="trust-row"><span>Response time</span><b>Excellent</b></div><div class="trust-row"><span>Salary transparency</span><b>High</b></div></section></div></section><p class="ethical-note">Feedback and employment signals require moderation, a right to respond, and an appeal. This local MVP demonstrates the workflow; it does not use reputation scores for ranking.</p>`; $('#post-job').onclick = () => $('#job-dialog').showModal(); } catch (error) { el.innerHTML = `<p class="error">${escape(error.message)}</p>`; } }
document.querySelectorAll('.mode').forEach((button) => button.addEventListener('click', () => { const user = JSON.parse(localStorage.getItem('careersync-user') || 'null'); if (user && ((button.dataset.view === 'employer' && !['employer', 'employer_admin', 'recruiter'].includes(user.role)) || (button.dataset.view === 'employee' && user.role !== 'employee'))) { message('This account can only access its assigned workspace.'); return; } document.querySelectorAll('.mode').forEach((item) => item.classList.toggle('active', item === button)); document.querySelectorAll('.view').forEach((view) => view.classList.toggle('active', view.id === button.dataset.view)); if (button.dataset.view === 'employer') renderEmployer(); else renderEmployee(); }));
document.addEventListener('click', async (event) => { const job = event.target.dataset.job; const page = event.target.dataset.employeePage; const schedule = event.target.dataset.schedule; if (page) { document.querySelectorAll('[data-employee-page]').forEach((b) => b.classList.toggle('nav-active', b.dataset.employeePage === page)); page === 'interviews' ? renderEmployeeInterviews() : renderEmployee(page); } if (schedule) { const dialog = $('#interview-dialog'); dialog.querySelector('[name="applicationId"]').value = schedule; $('#interview-candidate').textContent = `Invite ${event.target.dataset.candidate} to an online interview.`; dialog.showModal(); } if (job) { event.target.disabled = true; try { await api(`/api/jobs/${job}/apply`, { method: 'POST' }); event.target.textContent = 'Applied'; event.target.classList.add('done'); message('Application submitted — good luck, Aisha!'); } catch (error) { event.target.disabled = false; message(error.message); } } });
document.addEventListener('change', async (event) => { const applicationId = event.target.dataset.application; if (!applicationId) return; try { await api(`/api/employer/applications/${applicationId}`, { method: 'PATCH', body: JSON.stringify({ status: event.target.value }) }); message('Candidate status updated.'); } catch (error) { message(error.message); } });
$('#job-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.target); try { await api('/api/employer/jobs', { method: 'POST', body: JSON.stringify({ title: form.get('title'), category: form.get('category'), description: form.get('description'), location: form.get('location'), workMode: form.get('workMode'), employmentType: form.get('employmentType'), paymentFrequency: form.get('paymentFrequency'), minPay: form.get('minPay'), maxPay: form.get('maxPay'), workHoursPerDay: form.get('workHoursPerDay'), offDays: form.get('offDays'), paymentMethod: form.get('paymentMethod'), requiredSkills: form.get('skills').split(',') }) }); $('#job-dialog').close(); event.target.reset(); renderEmployer(); message('Job published with complete work and pay details.'); } catch (error) { message(error.message); } });
$('#interview-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.target); try { await api('/api/employer/interviews', { method: 'POST', body: JSON.stringify(Object.fromEntries(form)) }); $('#interview-dialog').close(); event.target.reset(); renderEmployerPage('candidates'); message('Interview invitation scheduled.'); } catch (error) { message(error.message); } });
async function renderAdmin() {
  const el = $('#admin-content'); el.innerHTML = '<p class="loading">Loading platform controls...</p>';
  try {
    const data = await api('/api/admin/dashboard'); const { metrics, companies, jobs, applications, auditEvents } = data;
    el.innerHTML = `<section class="metrics"><article><p>Total users</p><strong>${metrics.users}</strong><span class="positive">Active accounts</span></article><article><p>Companies</p><strong>${metrics.companies}</strong><span class="positive">Verification queue</span></article><article><p>Live jobs</p><strong>${metrics.activeJobs}</strong><span class="positive">Discoverable now</span></article><article><p>Applications</p><strong>${metrics.applications}</strong><span class="positive">Across platform</span></article></section><div class="admin-grid"><div class="admin-sections"><section class="panel"><div class="panel-head"><h2>Company verification</h2><span class="verified">Moderate</span></div><table class="admin-table"><thead><tr><th>COMPANY</th><th>TRUST</th><th>STATUS</th></tr></thead><tbody>${companies.map((c) => `<tr><td>${escape(c.displayName)}</td><td>${c.trustScore || '—'} / 5</td><td><select data-company="${c.id}"><option value="pending" ${c.verificationStatus === 'pending' ? 'selected' : ''}>Pending</option><option value="verified" ${c.verificationStatus === 'verified' ? 'selected' : ''}>Verified</option><option value="suspended" ${c.verificationStatus === 'suspended' ? 'selected' : ''}>Suspended</option></select></td></tr>`).join('')}</tbody></table></section><section class="panel"><div class="panel-head"><h2>Job moderation</h2><span>${jobs.length} listings</span></div><table class="admin-table"><thead><tr><th>ROLE</th><th>COMPANY</th><th>STATUS</th></tr></thead><tbody>${jobs.map((j) => `<tr><td>${escape(j.title)}</td><td>Northstar Labs</td><td><select data-admin-job="${j.id}"><option value="published" ${j.status === 'published' ? 'selected' : ''}>Published</option><option value="draft" ${j.status === 'draft' ? 'selected' : ''}>Draft</option><option value="closed" ${j.status === 'closed' ? 'selected' : ''}>Closed</option></select></td></tr>`).join('')}</tbody></table></section></div><div class="admin-sections"><section class="panel"><div class="panel-head"><h2>Applications</h2><span>${applications.length} total</span></div>${applications.length ? applications.map((a) => `<div class="trust-row"><span>${escape(a.status)}</span><b>${new Date(a.submittedAt).toLocaleDateString()}</b></div>`).join('') : '<div class="empty"><h3>No applications</h3><p>Platform activity will appear here.</p></div>'}</section><section class="panel"><div class="panel-head"><h2>Audit trail</h2><span>Latest events</span></div><ul class="audit-list">${auditEvents.length ? auditEvents.map((a) => `<li><strong>${escape(a.type.replaceAll('.', ' '))}</strong><small>${escape(a.detail)} · ${new Date(a.createdAt).toLocaleString()}</small></li>`).join('') : '<li>No activity yet.</li>'}</ul></section></div></div>`;
  } catch (error) { el.innerHTML = `<p class="error">${escape(error.message)}</p>`; }
}
async function renderEmployeeInterviews() {
  const el = $('#employee-content'); el.innerHTML = '<p class="loading">Loading interview reminders...</p>';
  try {
    const { reminders } = await api('/api/employee/reminders');
    el.innerHTML = `<p class="eyebrow">INTERVIEW REMINDERS</p><h1>Your upcoming<br />interviews</h1>${reminders.length ? reminders.map((item) => `<article class="interview-card ${item.due ? 'due' : ''}"><span class="reminder-label">${item.due ? 'REMINDER: within 24 hours' : 'INTERVIEW CONFIRMED'}</span><h3>${escape(item.job.title)}</h3><p>${new Date(item.scheduledAt).toLocaleString()} · ${escape(item.timezone)}</p><p>${escape(item.notes || 'Join on time and prepare your portfolio.')}</p><a class="meeting-link" href="${escape(item.meetingLink)}" target="_blank" rel="noreferrer">Join meeting →</a></article>`).join('') : '<div class="empty"><h3>No interview scheduled</h3><p>Interview invitations from employers will appear here.</p></div>'}`;
  } catch (error) { el.innerHTML = `<p class="error">${escape(error.message)}</p>`; }
}
async function renderEmployerPage(page) {
  if (page === 'overview') return renderEmployer();
  const el = $('#employer-content'); el.innerHTML = '<p class="loading">Loading...</p>';
  try {
    const { jobs, candidates, interviews } = await api('/api/employer/dashboard');
    if (page === 'jobs') {
      el.innerHTML = `<header class="dash-header"><div><p class="eyebrow">JOB MANAGEMENT</p><h1>Your job openings</h1></div><button class="primary" id="post-job">+ Post a job</button></header><section class="panel employer-list"><div class="panel-head"><div><h2>All openings</h2><p>Create, publish, and monitor your vacancies.</p></div><span class="verified">${jobs.filter((j) => j.status === 'published').length} live</span></div>${jobs.map((job) => `<article class="candidate job-row"><div class="company-logo lime">N</div><div class="candidate-info"><h3>${escape(job.title)}</h3><p>${escape(job.location)} · ${escape(job.workMode)} · ${escape(job.salary)}</p><div class="skills">${job.requiredSkills.map((skill) => `<span>${escape(skill)}</span>`).join('')}</div></div><span class="status ${job.status}">${escape(job.status)}</span></article>`).join('')}</section>`;
      $('#post-job').onclick = () => $('#job-dialog').showModal();
    } else if (page === 'interviews') {
      el.innerHTML = `<header class="dash-header"><div><p class="eyebrow">INTERVIEW SCHEDULE</p><h1>Upcoming interviews</h1></div></header><section class="panel"><div class="panel-head"><div><h2>Employer reminders</h2><p>A reminder is prepared for you and the candidate 24 hours before each interview.</p></div><span>${interviews.length} scheduled</span></div>${interviews.length ? interviews.map((item) => `<article class="interview-card"><span class="reminder-label">REMINDER AT ${new Date(item.employerReminderAt).toLocaleString()}</span><h3>Candidate interview</h3><p>${new Date(item.scheduledAt).toLocaleString()} · ${escape(item.timezone)}</p><p>${escape(item.notes || 'No preparation notes added.')}</p><a class="meeting-link" href="${escape(item.meetingLink)}" target="_blank" rel="noreferrer">Open meeting link →</a></article>`).join('') : '<div class="empty"><h3>No interviews scheduled</h3><p>Schedule an interview from the Candidates page.</p></div>'}</section>`;
    } else {
      el.innerHTML = `<header class="dash-header"><div><p class="eyebrow">CANDIDATE PIPELINE</p><h1>Review candidates</h1></div></header><section class="panel candidates"><div class="panel-head"><div><h2>All applicants</h2><p>Use match signals to support—not replace—your hiring judgement.</p></div><span>${candidates.length} applicants</span></div>${candidates.length ? candidates.map(candidateRow).join('') : '<div class="empty"><h3>No applications yet</h3><p>Applicants will appear here as candidates apply to your jobs.</p></div>'}</section>`;
    }
  } catch (error) { el.innerHTML = `<p class="error">${escape(error.message)}</p>`; }
}
document.addEventListener('click', (event) => {
  const page = event.target.dataset.employerPage;
  if (!page) return;
  document.querySelectorAll('[data-employer-page]').forEach((button) => button.classList.toggle('side-active', button.dataset.employerPage === page));
  renderEmployerPage(page);
});
document.addEventListener('change', async (event) => {
  const companyId = event.target.dataset.company; const jobId = event.target.dataset.adminJob;
  try {
    if (companyId) { await api(`/api/admin/companies/${companyId}`, { method: 'PATCH', body: JSON.stringify({ verificationStatus: event.target.value }) }); message('Company verification updated.'); }
    if (jobId) { await api(`/api/admin/jobs/${jobId}`, { method: 'PATCH', body: JSON.stringify({ status: event.target.value }) }); message('Job moderation status updated.'); }
  } catch (error) { message(error.message); }
});
// Add the offer destination without requiring a page reload or a separate app shell.
const loginForm = $('#login-form');
if (loginForm && !loginForm.querySelector('[name="role"]')) loginForm.querySelector('[name="identifier"]')?.closest('label')?.insertAdjacentHTML('beforebegin', '<label>Login workspace<select name="role"><option value="employee">Employee app</option><option value="employer">Employer portal</option></select></label>');
setTimeout(() => { const form = $('#login-form'); if (form && !form.querySelector('[name="role"]')) form.querySelector('[name="identifier"]')?.closest('label')?.insertAdjacentHTML('beforebegin', '<label>Login workspace<select name="role"><option value="employee">Employee app</option><option value="employer">Employer portal</option></select></label>'); }, 100);
const registrationName = $('#register-form [name="name"]');
if (registrationName && !$('#register-form [name="username"]')) registrationName.closest('label')?.insertAdjacentHTML('afterend', '<label>Username<input name="username" required minlength="3" maxlength="30" pattern="[A-Za-z0-9._-]+" placeholder="e.g. nur.aisyah" /><small>Use letters, numbers, dots, underscores, or hyphens.</small></label>');
const employeeNav = document.querySelector('.bottom-nav');
if ($('#install-app')) { $('#install-app').hidden = false; $('#install-app').textContent = '⇩ Install app'; }
if (employeeNav && !employeeNav.querySelector('[data-employee-page="offers"]')) employeeNav.insertAdjacentHTML('beforeend', '<button data-employee-page="offers">✦<span>Offers</span></button>');
const baseEmployerRender = renderEmployer;
renderEmployer = async function () { await baseEmployerRender(); try { const { notifications } = await api('/api/employer/notifications'); if (notifications?.length && !$('#employer-content .notification-banner')) $('#employer-content .dash-header')?.insertAdjacentHTML('afterend', `<section class="notification-banner employer-alert"><strong>${notifications.length} new update${notifications.length === 1 ? '' : 's'}</strong><span>${escape(notifications[0].title)} — ${escape(notifications[0].body)}</span></section>`); } catch {} };
async function renderEmployeeOffers() { const el = $('#employee-content'); el.innerHTML = '<p class="loading">Loading your offers…</p>'; try { const [{ offers }, { notifications }] = await Promise.all([api('/api/my-offers'), api('/api/my-notifications')]); el.innerHTML = `<p class="eyebrow">OFFERS & UPDATES</p><h1>Your next opportunity</h1>${notifications.length ? `<section class="notification-banner"><strong>${notifications.length} update${notifications.length === 1 ? '' : 's'}</strong><span>${escape(notifications[0].title)} — ${escape(notifications[0].body)}</span></section>` : ''}${offers.length ? offers.map((offer) => `<article class="offer-card"><div class="offer-card-head"><div><span class="eyebrow">CAREERSYNC OFFER</span><h2>${escape(offer.job?.title || offer.title)}</h2><p>Northstar Labs · issued ${new Date(offer.createdAt).toLocaleDateString()}</p></div><span class="offer-status ${offer.status}">${escape(offer.status)}</span></div><div class="offer-grid"><div><small>PAY</small><strong>${escape(offer.salary)}</strong><span>${escape(offer.payFrequency)}</span></div><div><small>WORKING TIME</small><strong>${escape(offer.workHoursPerDay || 8)} hrs/day</strong><span>Start date to confirm</span></div><div><small>EXPIRY</small><strong>${new Date(offer.expiresAt).toLocaleDateString()}</strong><span>Review before accepting</span></div></div>${offer.status === 'sent' ? `<div class="offer-actions"><button class="primary" data-offer-respond="${offer.id}" data-response="accepted">Accept offer</button><button class="outline" data-offer-respond="${offer.id}" data-response="declined">Decline</button></div>` : '<p class="offer-note">This offer has been recorded in your Career Passport.</p>'}</article>`).join('') : '<div class="empty"><h3>No offer letters yet</h3><p>When an employer shortlists you, your offer letter will appear here automatically.</p></div>'}`; } catch (error) { el.innerHTML = `<p class="error">${escape(error.message)}</p>`; } }
document.addEventListener('click', async (event) => { const page = event.target.dataset.employeePage; if (page === 'offers') { document.querySelectorAll('[data-employee-page]').forEach((b) => b.classList.toggle('nav-active', b.dataset.employeePage === page)); await renderEmployeeOffers(); } const offerId = event.target.dataset.offerRespond; if (offerId) { event.target.disabled = true; try { await api(`/api/offers/${offerId}/respond`, { method: 'PATCH', body: JSON.stringify({ status: event.target.dataset.response }) }); message(event.target.dataset.response === 'accepted' ? 'Offer accepted. The employer has been notified.' : 'Offer declined.'); renderEmployeeOffers(); } catch (error) { event.target.disabled = false; message(error.message); } } });
function updateAuthUI() { const account = $('#open-account'); const avatar = document.querySelector('.avatar'); const user = JSON.parse(localStorage.getItem('careersync-user') || 'null'); if (!account) return; if (user) { account.innerHTML = `<span class="account-user-name">${escape(user.name || 'Account')}</span><span>⌄</span>`; account.classList.add('signed-in'); if (avatar) { avatar.textContent = (user.name || 'U').split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase(); avatar.title = `${user.name} · ${user.role}`; avatar.classList.add('signed-in-avatar'); } if (!document.querySelector('.signed-in-strip')) document.querySelector('.topbar').insertAdjacentHTML('afterend', `<div class="signed-in-strip"><span>Signed in as <strong>${escape(user.name)}</strong></span><span class="role-chip">${escape(user.role === 'employer' ? 'Employer workspace' : 'Employee workspace')}</span><button id="logout-account" class="text-button">Log out</button></div>`); } else { account.innerHTML = 'Account <span>⌄</span>'; account.classList.remove('signed-in'); document.querySelector('.signed-in-strip')?.remove(); if (avatar) { avatar.textContent = 'AT'; avatar.classList.remove('signed-in-avatar'); } } }
document.addEventListener('click', async (event) => { if (event.target.id !== 'logout-account') return; try { await api('/api/auth/logout', { method: 'POST' }); } catch {} localStorage.removeItem('careersync-user'); localStorage.removeItem('careersync-session'); updateAuthUI(); document.querySelectorAll('.view').forEach((view) => view.classList.toggle('active', view.id === 'employee')); document.querySelectorAll('.mode').forEach((button) => button.classList.toggle('active', button.dataset.view === 'employee')); renderEmployee(); message('You have been logged out safely.'); });
function finishLogin(result) { localStorage.setItem('careersync-user', JSON.stringify(result.user)); localStorage.setItem('careersync-session', result.session.token); localStorage.setItem('careersync-session-expires', String(result.session.expiresAt || (Date.now() + 300000))); updateAuthUI(); $('#login-dialog').close(); const isEmployer = ['employer', 'employer_admin', 'recruiter'].includes(result.user.role); document.querySelectorAll('.view').forEach((view) => view.classList.toggle('active', view.id === (isEmployer ? 'employer' : 'employee'))); document.querySelectorAll('.mode').forEach((button) => { button.classList.toggle('active', button.dataset.view === (isEmployer ? 'employer' : 'employee')); button.hidden = true; }); isEmployer ? renderEmployer() : renderEmployee(); message(`Welcome back, ${result.user.name}.`); }
const storedIdentity = JSON.parse(localStorage.getItem('careersync-user') || 'null');
if (storedIdentity?.id === 'usr_aisha' || /prototype/i.test(storedIdentity?.name || '')) { localStorage.removeItem('careersync-user'); localStorage.removeItem('careersync-session'); }
const identityObserver = new MutationObserver(() => { const user = JSON.parse(localStorage.getItem('careersync-user') || 'null'); if (!user) return; const portrait = document.querySelector('#employee-content .portrait'); if (portrait) portrait.textContent = user.name.split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase(); const hello = document.querySelector('#employee-content .hello p'); if (hello) hello.textContent = `${document.querySelectorAll('#employee-content .job-card').length} live opportunities ranked for ${user.name}.`; });
identityObserver.observe($('#employee-content'), { childList: true, subtree: true });
setTimeout(() => identityObserver.disconnect(), 0);
updateAuthUI();
renderEmployee();
if ($('#open-account')) $('#open-account').addEventListener('click', () => $('#account-dialog').showModal());
if ($('#close-account')) $('#close-account').addEventListener('click', () => $('#account-dialog').close());
if ($('#account-login')) $('#account-login').addEventListener('click', () => { $('#account-dialog').close(); $('#login-dialog').showModal(); });
if ($('#account-register')) $('#account-register').addEventListener('click', () => { $('#account-dialog').close(); $('#register-dialog').showModal(); });
if ($('#account-security')) $('#account-security').addEventListener('click', () => { $('#account-dialog').close(); $('#security-dialog').showModal(); });
if ($('#register-role')) $('#register-role').addEventListener('change', (event) => { $('#company-name-label').hidden = event.target.value !== 'employer'; });
if ($('#profile-picture')) $('#profile-picture').addEventListener('change', (event) => { const file = event.target.files[0]; if (!file) return; if (file.size > 2000000) { message('Please choose an image smaller than 2 MB.'); event.target.value = ''; return; } const reader = new FileReader(); reader.onload = () => { $('#profile-image-data').value = reader.result; $('#profile-photo-preview').style.backgroundImage = `url(${reader.result})`; $('#profile-photo-preview').textContent = ''; }; reader.readAsDataURL(file); });
if ($('#register-form')) $('#register-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = new FormData(event.target); const payload = Object.fromEntries(form); delete payload.profilePictureFile; payload.profileVisibility = form.get('profileVisibility') ? 'hiring_only' : 'private'; try { const result = await api('/api/auth/register', { method: 'POST', body: JSON.stringify(payload) }); $('#register-dialog').close(); event.target.reset(); $('#company-name-label').hidden = true; $('#profile-image-data').value = ''; $('#profile-photo-preview').style.backgroundImage = ''; $('#profile-photo-preview').textContent = '+'; message(result.message); } catch (error) { message(error.message); } });
if ($('#interview-mode')) $('#interview-mode').addEventListener('change', (event) => { const online = event.target.value === 'online'; $('#meeting-link-label').hidden = !online; $('#meeting-link-label input').required = online; $('#meeting-location-label').hidden = online; $('#meeting-location-label input').required = !online; });
if ($('#job-category')) api('/api/categories').then(({ categories }) => { $('#job-category').innerHTML = categories.map((category) => `<option>${escape(category)}</option>`).join(''); }).catch(() => { $('#job-category').innerHTML = '<option>Other</option>'; });
document.addEventListener('change', (event) => { if (event.target.id !== 'employee-category-filter') return; document.querySelectorAll('#job-results .job-card').forEach((card) => { card.hidden = event.target.value !== 'all' && card.dataset.category !== event.target.value; }); });
if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('/sw.js').catch(() => {}));
let deferredInstallPrompt = null;
window.addEventListener('beforeinstallprompt', (event) => { event.preventDefault(); deferredInstallPrompt = event; if ($('#install-app')) $('#install-app').hidden = false; });
let inactivityTimer;
function startInactivityTimer() { clearTimeout(inactivityTimer); if (!localStorage.getItem('careersync-session')) return; inactivityTimer = setTimeout(async () => { try { await api('/api/auth/logout', { method: 'POST' }); } catch {} localStorage.removeItem('careersync-user'); localStorage.removeItem('careersync-session'); localStorage.removeItem('careersync-session-expires'); updateAuthUI(); document.querySelectorAll('.view').forEach((view) => view.classList.toggle('active', view.id === 'employee')); message('You were logged out after 5 minutes of inactivity.'); }, 5 * 60 * 1000); }
['click', 'keydown', 'touchstart', 'mousemove'].forEach((eventName) => document.addEventListener(eventName, () => { if (localStorage.getItem('careersync-session')) startInactivityTimer(); }, { passive: true }));
startInactivityTimer();
const originalFinishLogin = finishLogin;
finishLogin = (result) => { originalFinishLogin(result); startInactivityTimer(); applyWorkspaceLock(); refreshNotificationCentre(); };
function applyWorkspaceLock() { const user = JSON.parse(localStorage.getItem('careersync-user') || 'null'); document.querySelectorAll('.mode').forEach((button) => { button.hidden = !!user; }); }
applyWorkspaceLock();
document.addEventListener('click', (event) => { if (event.target.id === 'logout-account') { clearTimeout(inactivityTimer); document.querySelectorAll('.mode').forEach((button) => { button.hidden = false; }); } });
async function refreshNotificationCentre() { const user = JSON.parse(localStorage.getItem('careersync-user') || 'null'); if (!user || !$('#notification-centre')) return; const endpoint = ['employer', 'employer_admin', 'recruiter'].includes(user.role) ? '/api/employer/notifications' : '/api/my-notifications'; try { const data = await api(endpoint); const list = data.notifications || []; $('#notification-centre').textContent = list.length ? `🔔 ${list.length}` : '🔔'; $('#notification-centre').title = list.length ? `${list.length} new notification${list.length === 1 ? '' : 's'}` : 'No new notifications'; } catch {} }
if ($('.mode-switch') && !$('#notification-centre')) { $('.mode-switch').insertAdjacentHTML('afterend', '<button class="notification-centre" id="notification-centre" aria-label="Notifications">🔔</button>'); $('#notification-centre').addEventListener('click', async () => { const user = JSON.parse(localStorage.getItem('careersync-user') || 'null'); if (!user) return message('Log in to view notifications.'); const endpoint = ['employer', 'employer_admin', 'recruiter'].includes(user.role) ? '/api/employer/notifications' : '/api/my-notifications'; try { const data = await api(endpoint); const list = data.notifications || []; message(list.length ? list.slice(0, 2).map((item) => item.title).join(' · ') : 'You have no new notifications.'); } catch (error) { message(error.message); } }); }
refreshNotificationCentre();
// Native APKs are already installed; keep the download prompt for the website only.
const isNativeApp = !!(window.Capacitor?.isNativePlatform?.() || /Capacitor/i.test(navigator.userAgent));
document.body.classList.toggle('native-app', isNativeApp);
if (isNativeApp) { $('#install-app')?.remove(); }
function closeAuthGate() { $('#auth-gate')?.remove(); document.body.classList.remove('auth-gate-active'); }
function showSettings() {
  const user = JSON.parse(localStorage.getItem('careersync-user') || 'null'); if (!user) return message('Please log in first.');
  if (!$('#settings-dialog')) document.body.insertAdjacentHTML('beforeend', `<dialog id="settings-dialog"><section class="settings-panel"><div class="modal-head"><div><p class="eyebrow">ACCOUNT SETTINGS</p><h2>Make CareerSync yours</h2></div><button id="close-settings" aria-label="Close">×</button></div><div class="settings-profile"><div class="settings-avatar">${escape((user.name || 'U').split(/\s+/).map((part) => part[0]).join('').slice(0, 2).toUpperCase())}</div><div><strong>${escape(user.name)}</strong><span>${escape(user.email || '')}</span><small>${user.role === 'employee' ? 'Employee workspace' : 'Employer workspace'}</small></div></div><label>Display language<select><option>English</option><option>Bahasa Melayu</option><option>中文</option></select></label><label class="settings-toggle"><input type="checkbox" checked /> Email and in-app notifications</label><label class="settings-toggle"><input type="checkbox" /> Dark mode</label><button class="outline" id="settings-security">Open security & recovery</button><button class="primary" id="settings-done">Save settings</button></section></dialog>`);
  $('#settings-dialog').showModal(); $('#close-settings').onclick = () => $('#settings-dialog').close(); $('#settings-done').onclick = () => { $('#settings-dialog').close(); message('Settings saved.'); }; $('#settings-security').onclick = () => { $('#settings-dialog').close(); $('#security-dialog')?.showModal(); };
}
if ($('#account-dialog') && !$('#account-settings')) { $('.account-actions')?.insertAdjacentHTML('beforeend', '<button class="account-action" id="account-settings"><span>⚙</span><strong>Settings</strong><small>Profile, language and notifications</small></button>'); $('#account-settings').addEventListener('click', () => { $('#account-dialog').close(); showSettings(); }); }
function showAuthGate() {
  if (localStorage.getItem('careersync-session')) return;
  if (!$('#auth-gate')) { document.body.classList.add('auth-gate-active'); document.body.insertAdjacentHTML('afterbegin', `<section class="auth-gate" id="auth-gate"><div class="auth-gate-card"><div class="auth-gate-brand"><span class="brand-mark">↗</span> CareerSync <em>AI</em></div><p class="eyebrow">YOUR NEXT MOVE, MADE CLEAR</p><h1>Find work that fits your life.</h1><p class="auth-gate-lead">Discover verified opportunities, prepare with AI, and move from application to interview with confidence.</p><div class="auth-gate-benefits"><span>✦ Skills-first matching</span><span>✓ Verified employers</span><span>◷ Interview reminders</span><span>▣ Offers in one place</span></div><button class="primary auth-gate-login" id="gate-login">Log in securely</button><button class="outline auth-gate-register" id="gate-register">Create an account</button><small class="auth-gate-note">Choose Employee app or Employer portal during login. Your workspace stays private and protected.</small></div></section>`); }
  $('#gate-login').onclick = () => $('#login-dialog').showModal(); $('#gate-register').onclick = () => $('#register-dialog').showModal();
}
async function validateStoredSession() {
  if (!localStorage.getItem('careersync-session')) return showAuthGate();
  try { await api('/api/auth/session'); closeAuthGate(); }
  catch {
    localStorage.removeItem('careersync-user'); localStorage.removeItem('careersync-session'); localStorage.removeItem('careersync-session-expires');
    document.querySelectorAll('.mode').forEach((button) => { button.hidden = false; });
    showAuthGate();
  }
}
validateStoredSession();
const originalCloseAuthGate = closeAuthGate;
const priorFinishLogin = finishLogin;
finishLogin = (result) => { priorFinishLogin(result); originalCloseAuthGate(); };
refreshNotificationCentre();
setInterval(refreshNotificationCentre, 15000);
window.addEventListener('focus', refreshNotificationCentre);
document.addEventListener('visibilitychange', () => { if (!document.hidden) refreshNotificationCentre(); });
if ($('#install-app')) $('#install-app').addEventListener('click', async () => { if (!deferredInstallPrompt) { message('Use your browser menu and choose Install CareerSync AI or Add to Home screen.'); return; } deferredInstallPrompt.prompt(); await deferredInstallPrompt.userChoice; deferredInstallPrompt = null; $('#install-app').hidden = true; });
window.addEventListener('appinstalled', () => { if ($('#install-app')) $('#install-app').hidden = true; message('CareerSync AI was installed on your device.'); });
if ($('#open-assistant')) $('#open-assistant').addEventListener('click', () => $('#assistant-dialog').showModal());
if ($('#close-assistant')) $('#close-assistant').addEventListener('click', () => $('#assistant-dialog').close());
const userAssistantHistory = [];
async function streamAssistantReply(messageText, role, history, onText) { const response = await fetch('/api/assistant/stream', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: messageText, role, history }) }); if (!response.ok) throw new Error('Assistant is unavailable.'); const reader = response.body.getReader(); const decoder = new TextDecoder(); let buffer = ''; let answer = ''; let provider = 'local-fallback'; while (true) { const { value, done } = await reader.read(); if (done) break; buffer += decoder.decode(value, { stream: true }); const lines = buffer.split('\n'); buffer = lines.pop() || ''; for (const line of lines) { if (!line.startsWith('data:')) continue; const payload = line.slice(5).trim(); if (payload === '[DONE]') continue; try { const part = JSON.parse(payload); answer += part.text || ''; provider = part.provider || provider; onText(answer, provider); } catch {} } } return { answer, provider }; }
if ($('#assistant-form')) $('#assistant-form').addEventListener('submit', async (event) => { event.preventDefault(); const input = $('#assistant-input'); const messageText = input.value.trim(); if (!messageText) return; $('#assistant-messages').insertAdjacentHTML('beforeend', `<div class="assistant-message user">${escape(messageText)}</div><div class="assistant-message bot assistant-typing">Thinking...</div>`); const bot = $('#assistant-messages').lastElementChild; input.value = ''; try { const result = await streamAssistantReply(messageText, 'employee', userAssistantHistory, (answer) => { bot.textContent = answer; $('#assistant-messages').scrollTop = $('#assistant-messages').scrollHeight; }); userAssistantHistory.push({ role: 'user', text: messageText }, { role: 'model', text: result.answer }); } catch (error) { bot.textContent = error.message; } });
if ($('#open-security')) $('#open-security').addEventListener('click', () => $('#security-dialog').showModal());
if ($('#request-2fa')) $('#request-2fa').addEventListener('click', async () => { const email = $('#security-form [name="email"]').value; try { const result = await api('/api/auth/2fa/request', { method: 'POST', body: JSON.stringify({ email }) }); message(`${result.message} Local demo code: ${result.devCode}`); } catch (error) { message(error.message); } });
if ($('#verify-2fa')) $('#verify-2fa').addEventListener('click', async () => { const form = new FormData($('#security-form')); try { const result = await api('/api/auth/2fa/verify', { method: 'POST', body: JSON.stringify({ email: form.get('email'), code: form.get('code') }) }); message(result.message); $('#security-dialog').close(); } catch (error) { message(error.message); } });
if ($('#open-reset')) $('#open-reset').addEventListener('click', () => { $('#register-dialog').close(); $('#reset-dialog').showModal(); });
if ($('#request-reset')) $('#request-reset').addEventListener('click', async () => { const form = new FormData($('#reset-form')); try { const result = await api('/api/auth/password-reset/request', { method: 'POST', body: JSON.stringify({ identifier: form.get('identifier'), channel: form.get('channel') }) }); message(`${result.message} Local demo code: ${result.devCode}`); } catch (error) { message(error.message); } });
if ($('#confirm-reset')) $('#confirm-reset').addEventListener('click', async () => { const form = new FormData($('#reset-form')); try { const result = await api('/api/auth/password-reset/confirm', { method: 'POST', body: JSON.stringify({ identifier: form.get('identifier'), code: form.get('code'), newPassword: form.get('newPassword') }) }); message(result.message); $('#reset-dialog').close(); $('#reset-form').reset(); } catch (error) { message(error.message); } });
if ($('#open-login')) $('#open-login').addEventListener('click', () => $('#login-dialog').showModal());
if ($('#login-forgot')) $('#login-forgot').addEventListener('click', () => { $('#login-dialog').close(); $('#reset-dialog').showModal(); });
if ($('#login-password')) $('#login-password').addEventListener('click', async () => { const form = new FormData($('#login-form')); try { const result = await api('/api/auth/login/password', { method: 'POST', body: JSON.stringify({ identifier: form.get('identifier'), password: form.get('password') }) }); finishLogin(result); } catch (error) { message(error.message); } });
if ($('#request-login-code')) $('#request-login-code').addEventListener('click', async () => { const form = new FormData($('#login-form')); const identifier = String(form.get('identifier') || '').trim(); const channel = form.get('channel'); if (!identifier) { message(`Enter your registered ${channel === 'sms' ? 'phone number' : 'email'} first.`); $('#login-form [name="identifier"]').focus(); return; } if (channel === 'email' && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(identifier)) { message('Enter a valid registered email address.'); return; } if (channel === 'sms' && !/[0-9]{7,}/.test(identifier.replace(/\D/g, ''))) { message('Enter a valid registered phone number.'); return; } try { const result = await api('/api/auth/login/request', { method: 'POST', body: JSON.stringify({ identifier, channel }) }); message(`${result.message} ${result.devCode ? `Local development code: ${result.devCode}` : ''}`); } catch (error) { message(error.message); } });
if ($('#verify-login-code')) $('#verify-login-code').addEventListener('click', async () => { const form = new FormData($('#login-form')); try { const result = await api('/api/auth/login/verify', { method: 'POST', body: JSON.stringify({ identifier: form.get('identifier'), code: form.get('code') }) }); finishLogin(result); } catch (error) { message(error.message); } });
document.addEventListener('click', async (event) => { const applicationId = event.target.dataset.cancel; if (!applicationId) return; if (!window.confirm('Cancel this application? You can only cancel before interviewing or an offer.')) return; try { await api(`/api/applications/${applicationId}/cancel`, { method: 'PATCH' }); message('Application cancelled.'); renderEmployee('applications'); } catch (error) { message(error.message); } });
function enhanceEmployeeHome() {
  const content = $('#employee-content'); if (!content || content.querySelector('.mobile-insight') || !content.querySelector('.job-card')) return;
  const title = content.querySelector('.section-title');
  if (title) title.insertAdjacentHTML('beforebegin', '<section class="mobile-insight"><div class="insight-symbol">✦</div><div><span class="eyebrow">CAREER MOMENTUM</span><strong>One small step today</strong><p>Complete your portfolio to unlock more design and technology matches.</p></div><button id="mobile-coach">Coach →</button></section>');
  content.querySelectorAll('.job-card').forEach((card) => { if (card.querySelector('.save-job')) return; const apply = card.querySelector('.apply'); if (apply) apply.insertAdjacentHTML('beforebegin', `<button class="save-job" data-save="${apply.dataset.job}">${localStorage.getItem(`saved-${apply.dataset.job}`) ? 'Saved' : 'Save'}</button>`); });
  const coach = $('#mobile-coach'); if (coach) coach.onclick = () => $('#open-assistant')?.click();
}
const mobileObserver = new MutationObserver(() => enhanceEmployeeHome()); mobileObserver.observe($('#employee-content'), { childList: true });
document.addEventListener('click', (event) => { const saveId = event.target.dataset.save; if (!saveId) return; const key = `saved-${saveId}`; const saved = localStorage.getItem(key); if (saved) { localStorage.removeItem(key); event.target.textContent = 'Save'; message('Removed from saved jobs.'); } else { localStorage.setItem(key, 'true'); event.target.textContent = 'Saved'; message('Job saved for later.'); } });
